chore(deps): update all devdependencies (#66)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [prettier](https://prettier.io)
([source](https://redirect.github.com/prettier/prettier)) | [`3.5.3` ->
`3.6.2`](https://renovatebot.com/diffs/npm/prettier/3.5.3/3.6.2) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/prettier/3.6.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/prettier/3.6.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/prettier/3.5.3/3.6.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/prettier/3.5.3/3.6.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[prettier-plugin-packagejson](https://redirect.github.com/matzkoh/prettier-plugin-packagejson)
| [`2.5.15` ->
`2.5.17`](https://renovatebot.com/diffs/npm/prettier-plugin-packagejson/2.5.15/2.5.17)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/prettier-plugin-packagejson/2.5.17?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/prettier-plugin-packagejson/2.5.17?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/prettier-plugin-packagejson/2.5.15/2.5.17?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/prettier-plugin-packagejson/2.5.15/2.5.17?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>prettier/prettier (prettier)</summary>

###
[`v3.6.2`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#362)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.6.1...3.6.2)


[diff](https://redirect.github.com/prettier/prettier/compare/3.6.1...3.6.2)

##### Markdown: Add missing blank line around code block
([#&#8203;17675](https://redirect.github.com/prettier/prettier/pull/17675)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

````md
<!-- Input -->
1. Some text, and code block below, with newline after code block

   ```yaml
   ---
   foo: bar
   ```

   1. Another
   2. List

<!-- Prettier 3.6.1 -->
1. Some text, and code block below, with newline after code block

   ```yaml
   ---
   foo: bar
   ```
   1. Another
   2. List

<!-- Prettier 3.6.2 -->
1. Some text, and code block below, with newline after code block

   ```yaml
   ---
   foo: bar
   ```

   1. Another
   2. List
````

###
[`v3.6.1`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#361)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.6.0...3.6.1)


[diff](https://redirect.github.com/prettier/prettier/compare/3.6.0...3.6.1)

##### TypeScript: Allow const without initializer
([#&#8203;17650](https://redirect.github.com/prettier/prettier/pull/17650),
[#&#8203;17654](https://redirect.github.com/prettier/prettier/pull/17654)
by [@&#8203;fisker](https://redirect.github.com/fisker))

<!-- prettier-ignore -->

```jsx
// Input
export const version: string;

// Prettier 3.6.0 (--parser=babel-ts)
SyntaxError: Unexpected token (1:21)
> 1 | export const version: string;
    |                     ^

// Prettier 3.6.0 (--parser=oxc-ts)
SyntaxError: Missing initializer in const declaration (1:14)
> 1 | export const version: string;
    |              ^^^^^^^^^^^^^^^

// Prettier 3.6.1
export const version: string;
```

##### Miscellaneous: Avoid closing files multiple times
([#&#8203;17665](https://redirect.github.com/prettier/prettier/pull/17665)
by [@&#8203;43081j](https://redirect.github.com/43081j))

When reading a file to infer the interpreter from a shebang, we use the
`n-readlines` library to read the first line in order to get the
shebang.

This library closes files when it reaches EOF, and we later try close
the same
files again. We now close files only if `n-readlines` did not already
close
them.

###
[`v3.6.0`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#360)

[Compare
Source](https://redirect.github.com/prettier/prettier/compare/3.5.3...3.6.0)


[diff](https://redirect.github.com/prettier/prettier/compare/3.5.3...3.6.0)

🔗 [Release Notes](https://prettier.io/blog/2025/06/23/3.6.0)

</details>

<details>
<summary>matzkoh/prettier-plugin-packagejson
(prettier-plugin-packagejson)</summary>

###
[`v2.5.17`](https://redirect.github.com/matzkoh/prettier-plugin-packagejson/releases/tag/v2.5.17)

[Compare
Source](https://redirect.github.com/matzkoh/prettier-plugin-packagejson/compare/v2.5.16...v2.5.17)

##### Bug Fixes

- **deps:** update dependency sort-package-json to v3.3.1
([1435bf2](https://redirect.github.com/matzkoh/prettier-plugin-packagejson/commit/1435bf2b50eada65cc312ea80255f19cb957b0e5))

###
[`v2.5.16`](https://redirect.github.com/matzkoh/prettier-plugin-packagejson/releases/tag/v2.5.16)

[Compare
Source](https://redirect.github.com/matzkoh/prettier-plugin-packagejson/compare/v2.5.15...v2.5.16)

##### Bug Fixes

- **deps:** update dependency sort-package-json to v3.2.2
([8baedc1](https://redirect.github.com/matzkoh/prettier-plugin-packagejson/commit/8baedc1fa32cb80ad6d799c923d7e90d87a016d1))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - Between 12:00 AM and 03:59 AM, on day
1 of the month ( * 0-3 1 * * ) (UTC), Automerge - At any time (no
schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config
help](https://redirect.github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/xmldom/is-dom-node).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MC42Mi4xIiwidXBkYXRlZEluVmVyIjoiNDAuNjIuMSIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOlsiZGVwZW5kZW5jaWVzIiwicmVub3ZhdGUiXX0=-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>